/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('ingredient').del();
  await knex('ingredient').insert(
[
  { id: 1, ingredient: "Anchovy" },
  { id: 2, ingredient: "Bass" },
  { id: 3, ingredient: "Cod" },
  { id: 4, ingredient: "Flounder" },
  { id: 5, ingredient: "Haddock" },
  { id: 6, ingredient: "Halibut" },
  { id: 7, ingredient: "Herring" },
  { id: 8, ingredient: "Mackerel" },
  { id: 9, ingredient: "Pollock" },
  { id: 10, ingredient: "Salmon" },
  { id: 11, ingredient: "Snapper" },
  { id: 12, ingredient: "Surimi" },
  { id: 13, ingredient: "Tilapia" },
  { id: 14, ingredient: "Trout" },
  { id: 15, ingredient: "Tuna" },
  { id: 16, ingredient: "Fish broth" },
  { id: 17, ingredient: "Fish gelatin" },
  { id: 18, ingredient: "Fish oil" },
  { id: 19, ingredient: "Fish protein" },
  { id: 20, ingredient: "Fish sauce" },
  { id: 21, ingredient: "Isinglass" },
  { id: 22, ingredient: "Omega-3 (from fish)" },
  { id: 23, ingredient: "Butter" },
  { id: 24, ingredient: "Butterfat" },
  { id: 25, ingredient: "Buttermilk" },
  { id: 26, ingredient: "Casein" },
  { id: 27, ingredient: "Caseinate" },
  { id: 28, ingredient: "Cheese" },
  { id: 29, ingredient: "Condensed milk" },
  { id: 30, ingredient: "Cream" },
  { id: 31, ingredient: "Curds" },
  { id: 32, ingredient: "Evaporated milk" },
  { id: 33, ingredient: "Ghee" },
  { id: 34, ingredient: "Hydrolyzed casein" },
  { id: 35, ingredient: "Hydrolyzed whey protein" },
  { id: 36, ingredient: "Lactalbumin" },
  { id: 37, ingredient: "Lactoferrin" },
  { id: 38, ingredient: "Lactoglobulin" },
  { id: 39, ingredient: "Lactose" },
  { id: 40, ingredient: "Milk powder" },
  { id: 41, ingredient: "Milk protein" },
  { id: 42, ingredient: "Milk solids" },
  { id: 43, ingredient: "Nonfat dry milk" },
  { id: 44, ingredient: "Skim milk" },
  { id: 45, ingredient: "Whey" },
  { id: 46, ingredient: "Whey protein concentrate" },
  { id: 47, ingredient: "Almond" },
  { id: 48, ingredient: "Brazil nut" },
  { id: 49, ingredient: "Cashew" },
  { id: 50, ingredient: "Chestnut" },
  { id: 51, ingredient: "Coconut" },
  { id: 52, ingredient: "Hazelnut" },
  { id: 53, ingredient: "Macadamia nut" },
  { id: 54, ingredient: "Marzipan" },
  { id: 55, ingredient: "Nut butters" },
  { id: 56, ingredient: "Nut extracts" },
  { id: 57, ingredient: "Nut flour" },
  { id: 58, ingredient: "Nut meal" },
  { id: 59, ingredient: "Nut oils (walnut oil, almond oil)" },
  { id: 60, ingredient: "Pecan" },
  { id: 61, ingredient: "Pine nut" },
  { id: 62, ingredient: "Pistachio" },
  { id: 63, ingredient: "Walnut" },
  { id: 64, ingredient: "Arachis oil (peanut oil)" },
  { id: 65, ingredient: "Groundnuts" },
  { id: 66, ingredient: "Hydrolyzed peanut protein" },
  { id: 67, ingredient: "Mandelona nuts" },
  { id: 68, ingredient: "Nut meal (may contain peanuts)" },
  { id: 69, ingredient: "Peanut butter" },
  { id: 70, ingredient: "Peanut flour" },
  { id: 71, ingredient: "Peanut oil (cold-pressed, unrefined)" },
  { id: 72, ingredient: "Peanut protein" },
  { id: 73, ingredient: "Barnacle" },
  { id: 74, ingredient: "Crab" },
  { id: 75, ingredient: "Crawfish" },
  { id: 76, ingredient: "Krill" },
  { id: 77, ingredient: "Lobster" },
  { id: 78, ingredient: "Clam" },
  { id: 79, ingredient: "Mussel" },
  { id: 80, ingredient: "Oyster" },
  { id: 81, ingredient: "Scallop" },
  { id: 82, ingredient: "Octopus" },
  { id: 83, ingredient: "Prawn" },
  { id: 84, ingredient: "Shrimp" },
  { id: 85, ingredient: "Squid" },
  { id: 86, ingredient: "Shellfish stock" },
  { id: 87, ingredient: "Fish sauce" },
  { id: 88, ingredient: "Surimi" },
  { id: 89, ingredient: "Atta" },
  { id: 90, ingredient: "Bran" },
  { id: 91, ingredient: "Bulgur" },
  { id: 92, ingredient: "Couscous" },
  { id: 93, ingredient: "Durum" },
  { id: 94, ingredient: "Einkorn" },
  { id: 95, ingredient: "Emmer" },
  { id: 96, ingredient: "Farina" },
  { id: 97, ingredient: "Farro" },
  { id: 98, ingredient: "Flour (white, wheat, enriched)" },
  { id: 99, ingredient: "Kamut" },
  { id: 100, ingredient: "Malt extract" },
  { id: 101, ingredient: "Malt flavoring" },
  { id: 102, ingredient: "Modified wheat starch" },
  { id: 103, ingredient: "Seitan" },
  { id: 104, ingredient: "Semolina" },
  { id: 105, ingredient: "Spelt" },
  { id: 106, ingredient: "Triticale" },
  { id: 107, ingredient: "Vital wheat gluten" },
  { id: 108, ingredient: "Wheat bran" },
  { id: 109, ingredient: "Wheat flour" },
  { id: 110, ingredient: "Wheat germ" },
  { id: 111, ingredient: "Wheat starch" },
  { id: 112, ingredient: "Albumin" },
  { id: 113, ingredient: "Egg white" },
  { id: 114, ingredient: "Egg yolk" },
  { id: 115, ingredient: "Egg solids" },
  { id: 116, ingredient: "Egg powder" },
  { id: 117, ingredient: "Globulin" },
  { id: 118, ingredient: "Lecithin (if egg-based)" },
  { id: 119, ingredient: "Lysozyme" },
  { id: 120, ingredient: "Mayonnaise" },
  { id: 121, ingredient: "Meringue" },
  { id: 122, ingredient: "Ovalbumin" },
  { id: 123, ingredient: "Ovomucoid" },
  { id: 124, ingredient: "Ovovitellin" },
  { id: 125, ingredient: "Edamame" },
  { id: 126, ingredient: "Hydrolyzed soy protein" },
  { id: 127, ingredient: "Hydrolyzed vegetable protein (HVP)" },
  { id: 128, ingredient: "Lecithin (soy-based)" },
  { id: 129, ingredient: "Miso" },
  { id: 130, ingredient: "Natto" },
  { id: 131, ingredient: "Soy albumin" },
  { id: 132, ingredient: "Soy concentrate" },
  { id: 133, ingredient: "Soy flour" },
  { id: 134, ingredient: "Pork" },
  { id: 135, ingredient: "Bacon" },
  { id: 136, ingredient: "Ham" },
  { id: 137, ingredient: "Lard" },
  { id: 138, ingredient: "Gelatin" },
  { id: 139, ingredient: "Ethanol" },
  { id: 140, ingredient: "Beer" },
  { id: 141, ingredient: "Wine" },
  { id: 142, ingredient: "Alcohol" },
  { id: 143, ingredient: "Rennet" },
  { id: 144, ingredient: "Blood" },
  { id: 145, ingredient: "Enzymes" },
  { id: 146, ingredient: "Beef" },
  { id: 147, ingredient: "Chicken" },
  { id: 148, ingredient: "Honey" },
]);};